### ISSUE TITLE
Use unique typeface for post titles

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#50]

**Comment by dylan-k** [comment]
Would you like to use the Sans-Serif typeface for this? The site already has [Open Sans](http://www.google.com/fonts/specimen/Open+Sans) in use in many other places anyway.

**Comment by realpants** [comment]
If you think that's best, it's okay with me. But I was thinking it'd be
nice to have a unique and distinctive typeface for our titles, such as the
New Yorker does.

**Comment by dylan-k** [comment]
[The New Yorker's latest design on the web](http://gizmodo.com/how-the-new-yorker-redesigned-for-the-first-time-in-13-1325328771) has a custom-made typeface that was cut especially for them and they also use Neutraface, for which they have a custom license for use on the web. Nobody else can use it on the web, so far as I can tell. 

I imagine you don't have the budget for something like a custom typeface or a license like that but could you elaborate on what you mean by "unique and distinctive"? There might be something readily available, for free or for sale, something that would give the kind of typographic impression that you want to make. I imagine that uniqueness is important but new-yorker-ness maybe not so much, since they have that whole New Yorker vibe going on. This is about the Real Pants vibe, which is different.

You probably already know this stuff but if it helps to have [some vocabulary for talking about the various qualities that typefaces have](http://www.noupe.com/essentials/icons-fonts/a-crash-course-in-typography-the-basics-of-type.html), so you can say what you like and dislike, I think that this guide is a useful one.

**Comment by realpants** [comment]
At some point I had selected a type family for serif and san serif, but I can't find it anywhere. You're right that it wasn't a totally custom face. What I found was free (limited to a small part of the family) and web-ready. I'll find something else ... they abound.

**Comment by dylan-k** [comment]
I was looking for that too. I remember it. Where did that post go? I'll look for it too.

**Comment by realpants** [comment]
I found it! Questa Sans Regular. I forwarded it to you separately.
