### ISSUE TITLE
I can't tell what it is exactly, but the content column of pages is wider than posts

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#56]
Look at the social sharing icons for reference

**Comment by dylan-k** [comment]
here's the related CSS:

```
#primary>article {
/* padding: 20px 40px; */
}
```

that 40px padding on the left and right effectively makes the articles 80px less wide than pages.

in html the pages do not get contained within the `article` tag, although they should be, which is why they appear wider.

so my fix needs two parts:

- add article tag to pages
- remove padding from article tag in css
