### ISSUE TITLE
strange colon effect

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#65]
Richard Chiem let me know that his post http://realpants.com/mr-dobson-may-wong/ is having an issue formatting correctly. There are four lines in the poem that are errant: 

Carnations // : to undo 

and 

such dazed looks // : Human, we must love.

The colon disappears, and causes the line before it to be bold.

**Comment by dylan-k** [comment]
This is caused by a conflict with [the Markdown settings](http://en.support.wordpress.com/markdown/). It thinks that a line that starts with a colon is supposed to indication a definition list. 

The simplest fix here is to disable the markdown settings in Jetpack. I suppose that I'm the only author who uses it for posts, and Discus won't use it for comments, so there's probably no noticeable difference with it off.

For the other poetry-formatting issues that may crop up from time to time, there's always an option to wrap the entire poem in the `<pre>` tag. The styleguide may want to address how to do markup for poetry. I can point some good references on the topic, if that helps.

**Comment by dylan-k** [comment]
For the markup I think works best try the example on the section on [this page](http://uvatango.wordpress.com/class-materials/tei-handout-poetry-edition/) labelled "Poetry and Lists" but I realize that WYSIWYG writers and editors aren't going to gravitate to this without some help.
