### ISSUE TITLE
Commenting peculiarity

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#66]
After editing today's Eat | Read (http://realpants.com/eat-read-kristen-iskandrian-sarah-jean-alexander/), the comments on the post closed. It said "Comments are closed" at the bottom of the post. I went back in to edit the post and noticed there is a "Comments" field there, so I put in a test comment and that seemed to bring the comments back to the post. 

Some notes:

-I have never noticed this Comments field on the post editor before.
-My "test" did not show up on the post, but it did show up in the recent comments.
-Amy was able to put in a comment from the published post.
-The "# Comments" no longer appears on this post's bottom info line anymore.

**Comment by dylan-k** [comment]
The comments functionality of Realpants is more complex than the default, because Discus is acting on top of that default, but [here are some things to keep in mind about that default functionality](http://en.support.wordpress.com/enable-disable-comments/):

- comments can be enabled/disabled globally, for the entire site
- the controls for that are located at settings > discussion
- comments can be enabled/disabled for an indivudual post or page (these settings will override the global ones)
- there is a comments fields on the admin for every post/page, although it can be hidden. perhaps another user toggled its visibility and that affected you somehow?

As I understand it, Discus and Wordpress are acting together to provide moderation controls that affect whether a comment appears. Discus says "comments must be approved before they appear" however wordpress also says "if somebody already has an approved comment, go ahead and show it"

Now, with the default behavior out of the way, let's look to see what's behaving abnormally.

1. **a test comment did not appear on the post, but it did appear listed in the admin** 

I was unable to repeat this behavior. [I tried a test comment](http://realpants.com/eat-read-kristen-iskandrian-sarah-jean-alexander/#comment-1784534226), but it showed up right away. Can you try testing this again? Does it matter whether or not you are logged into Discus? Whether you have a previously approved comment?

2. **The "# Comments" no longer appears on this post's bottom info line anymore.**

It can get confusing sometimes: which page template, or location within a template, do you mean? If you mean views like the main index, the content count does display beneath the content of each post listed. It appears as part of the Discus embed on the individual post pages. Can you show a screenshot of where you would like the comments count to appear in addition to those places?

**Comment by realpants** [comment]
Thanks for the thorough foundation/explanation. I just posted another
comment through the comments field on the post editing admin and it shows
up in the Recent Comments widget, but not on the post. I don't think this
will ever be a needed function, though -- who would comment on the back end
rather than through the front end?

**Comment by realpants** [comment]
![screen shot 2015-01-10 at 11 51 42 am](https://cloud.githubusercontent.com/assets/10034861/5692334/7c060d00-98bf-11e4-9f48-17ff2adf3711.png)
This image shows the one and only place where the # Comments does not appear. Other than in this weird instance, the count appears everywhere else in the main index.

**Comment by dylan-k** [comment]
I see your test comment about croutons. It made it to wordpress, which is why the "recent comments" widget is able to display the comment. I logged into the Discus admin to look for the comment there, but there's no sign that the comment ever made it over to Discus, which would prevent it from appearing on the post. 

If Wordpress and Discus ever get out of sync like this, you can do something about it. On the Dashboad, go to Comments > Disqus and do "Export comments to Disqus". I tried this and it seems to work.
