### ISSUE TITLE
Responsive images and videos

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#73]
Some images are responsive, and some aren't. Videos aren't responsive.

**Comment by dylan-k** [comment]
Can you share some examples of the ones that are not responsive? I can work
to make the responsive CSS more aware of these cases.

Since the "fancypants" theme uses Bootstrap as its core HTML and CSS
markup, the Bootstrap guide shows some handy tricks for ensuring that
images and videos will be responsive.

for images: http://getbootstrap.com/css/#images
for videos: http://getbootstrap.com/components/#responsive-embed

These methods ought to work just fine wherever you use them on the site.
Let me know if you have trouble with them. Meanwhile, I'll take a look at
any examples of what's not currently working and add provisions for those
sorts of things.

**Comment by realpants** [comment]
Thanks for those links, I'll check out the knowledge base.

The most recent Eat Read (sorry I'm on my phone so no link) is
interesting-- it has a responsive and not responsive image in it.

All the comics are responsive, I think.

The Scene Report is not responsive.

In general, they aren't. I'm always pleasantly surprised when they are.

Let me know if you need more, and I'll read those links.

**Comment by dylan-k** [comment]
Starting with the first example, the most recent Eat Read...

The author entered a caption for the first (responsive) image, but not for the (unresponsive) second. This causes Wordpress to use different markup, for the different cases. The theme was built to prefer images that have captions, so I'll add a provision for what to do if a caption is not included with an image. I suspect the fix for this will apply likewise to the other examples you gave.

**Comment by dylan-k** [comment]
Images should be fixed by the last commit, but you also mentioned videos.
